import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Package each adapter independently; never copy or synchronize migration histories.
for (const adapter of ["sqlite", "durable-object", "postgresql"]) {
  verifyMigrations(adapter);
}

function verifyMigrations(adapter: string): void {
  const directory = new URL(
    `../src/modules/memory/infrastructure/persistence/${adapter}/migrations/`,
    import.meta.url,
  );
  const files = readdirSync(directory)
    .filter(
      (file) =>
        file.endsWith(".sql") ||
        (adapter === "postgresql" && file.endsWith(".ts")),
    )
    .sort();
  const sqlite = adapter === "sqlite";
  const scripts = files.filter((file) => file.endsWith(".ts"));
  const up = files.filter((file) =>
    sqlite ? file.includes(".do.") : file.endsWith(".up.sql"),
  );
  if (up.length === 0 || files.length !== up.length * 2 + scripts.length)
    throw new Error("Every migration needs one SQL pair");
  const pins: Record<string, string> = {};
  const ordered = [...up, ...scripts].sort();
  const migrations = ordered.map((file, index) => {
    if (file.endsWith(".ts")) {
      if (
        !new RegExp(`^${String(index + 1).padStart(6, "0")}_\\w+\\.ts$`).test(
          file,
        )
      )
        throw new Error("Migration versions must be continuous");
      const bytes = readFileSync(new URL(file, directory));
      pins[file] = createHash("sha256").update(bytes).digest("hex");
      return {
        idMonotonicInc: index + 1,
        description: file.slice(7, -3),
        sql: "",
      };
    }
    if (
      !new RegExp(
        sqlite
          ? `^${String(index + 1).padStart(6, "0")}\\.do\\.\\w+\\.sql$`
          : `^${String(index + 1).padStart(6, "0")}_\\w+\\.up\\.sql$`,
      ).test(file)
    )
      throw new Error("Migration versions must be continuous");
    const down = sqlite
      ? file.replace(".do.", ".undo.")
      : file.replace(".up.sql", ".down.sql");
    if (!files.includes(down)) throw new Error(`Missing reversal: ${down}`);
    for (const name of [file, down]) {
      const bytes = readFileSync(new URL(name, directory));
      if (!bytes.toString("utf8").trim())
        throw new Error(`Empty migration: ${name}`);
      pins[name] = createHash("sha256").update(bytes).digest("hex");
    }
    return {
      idMonotonicInc: index + 1,
      description: sqlite ? file.slice(10, -4) : file.slice(7, -7),
      sql: readFileSync(new URL(file, directory), "utf8"),
    };
  });
  const reversals = up.map((file, index) => ({
    idMonotonicInc: index + 1,
    sql: readFileSync(
      new URL(
        sqlite
          ? file.replace(".do.", ".undo.")
          : file.replace(".up.sql", ".down.sql"),
        directory,
      ),
      "utf8",
    ),
  }));
  const bundles = Object.entries({ migrations, reversals }).map(
    ([name, value]) => ({
      file: new URL(`${name}.generated.ts`, directory),
      content: `// Generated by scripts/generate-migrations.ts. Edit versioned SQL, then run migrations:generate.\nexport const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`,
    }),
  );
  const checksumFile = new URL("checksums.json", directory);
  if (process.argv.includes("--write")) {
    writeFileSync(checksumFile, JSON.stringify(pins, null, 2) + "\n");
    if (adapter !== "postgresql") {
      for (const bundle of bundles) writeFileSync(bundle.file, bundle.content);
    }
    console.log(
      `${adapter}: wrote SHA-256 pins${adapter === "postgresql" ? "" : " and SQL bundle"}.`,
    );
  } else {
    if (
      readFileSync(checksumFile, "utf8") !==
      JSON.stringify(pins, null, 2) + "\n"
    )
      throw new Error(
        `${adapter}: migration checksum mismatch; review SQL changes before regenerating`,
      );
    if (adapter !== "postgresql") {
      for (const bundle of bundles) {
        if (readFileSync(bundle.file, "utf8") !== bundle.content)
          throw new Error(
            `Stale migration bundle: ${fileURLToPath(bundle.file)}`,
          );
      }
    }
    console.log(
      `${adapter}: verified ${migrations.length} migration(s), checksums${adapter === "postgresql" ? "" : ", and SQL bundle"}.`,
    );
  }
}
