import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Build-time SQL packaging only. durable-utils owns migration execution and state.
const directory = new URL(
  "../src/memory/infrastructure/persistence/migrations/",
  import.meta.url,
);
const files = readdirSync(directory)
  .filter((file) => file.endsWith(".sql"))
  .sort();
const up = files.filter((file) => file.endsWith(".up.sql"));
if (up.length === 0 || files.length !== up.length * 2)
  throw new Error("Every migration needs one SQL pair");
const pins: Record<string, string> = {};
const migrations = up.map((file, index) => {
  if (
    !new RegExp(`^${String(index + 1).padStart(6, "0")}_\\w+\\.up\\.sql$`).test(
      file,
    )
  )
    throw new Error("Migration versions must be continuous");
  const down = file.replace(".up.sql", ".down.sql");
  if (!files.includes(down)) throw new Error(`Missing reversal: ${down}`);
  for (const name of [file, down]) {
    const bytes = readFileSync(new URL(name, directory));
    if (!bytes.toString("utf8").trim())
      throw new Error(`Empty migration: ${name}`);
    pins[name] = createHash("sha256").update(bytes).digest("hex");
  }
  return {
    idMonotonicInc: index + 1,
    description: file.slice(7, -7),
    sql: readFileSync(new URL(file, directory), "utf8"),
  };
});
const reversals = up.map((file, index) => ({
  idMonotonicInc: index + 1,
  sql: readFileSync(
    new URL(file.replace(".up.sql", ".down.sql"), directory),
    "utf8",
  ),
}));
const generated = `// Generated by scripts/generate-migrations.ts. Edit versioned SQL, then run migrations:generate.\nexport const migrations = ${JSON.stringify(migrations, null, 2)} as const;\nexport const reversals = ${JSON.stringify(reversals, null, 2)} as const;\n`;
const checksumFile = new URL("checksums.json", directory);
const generatedFile = new URL("generated.ts", directory);
if (process.argv.includes("--write")) {
  writeFileSync(checksumFile, JSON.stringify(pins, null, 2) + "\n");
  writeFileSync(generatedFile, generated);
  console.log("Generated migration bundle and SHA-256 pins.");
} else {
  if (
    readFileSync(checksumFile, "utf8") !==
    JSON.stringify(pins, null, 2) + "\n"
  )
    throw new Error(
      "Migration checksum mismatch; review SQL changes before regenerating",
    );
  if (readFileSync(generatedFile, "utf8") !== generated)
    throw new Error(`Stale migration bundle: ${fileURLToPath(generatedFile)}`);
  console.log(
    `Verified ${migrations.length} migration pair(s), checksums, and generated SQL bundle.`,
  );
}
