// Generated by scripts/generate-migrations.ts. Edit versioned SQL, then run migrations:generate.
export const reversals = [
  {
    "idMonotonicInc": 1,
    "sql": "-- Destructive baseline reversal. Recovery requires a separately verified backup.\n-- Never executed by the Worker or an RPC endpoint.\nDROP TABLE operations;\nDROP TABLE revisions;\nDROP TABLE state;\n"
  }
] as const;
